services:
  postgres:
    image: postgres:15
    container_name: gamehub_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: gamehub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
